examination/urls.py
from django.urls import path

from examination import views

app_name = "examination_app"

urlpatterns = [
    path('create', views.create, name='create'),
    path('view/all', views.view_all, name='view_all'),
    path('update/<int:pk>', views.update, name='update'),
    path('update/post', views.update_post, name='update_post'),
]

examination_body/urls.py
from django.urls import path

from examination_body import views

app_name = "examination_body_app"

urlpatterns = [
    path('create', views.create, name='create'),
    path('view/all', views.view_all, name='view_all'),
    path('update/<int:pk>', views.update, name='update'),
    path('update/post', views.update_post, name='update_post'),
]

muungano_online_exams/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('examination/', include('examination.urls')),
    path('examination/body/', include('examination_body.urls')),
    path('examination/paper/', include('examination_paper.urls')),
]

examination_body/models.py
from django.db import models

from user_management.models import User
# Create your models here.

class ExaminationBody(models.Model):
    class Meta:
        db_table = "examination_body"

    slug = models.SlugField(max_length=255, null = True, blank = True)
    name = models.CharField(max_length=255, null = False, blank = False)
    acronym = models.CharField(max_length=255, null = False, blank = False)
    created_by = models.ForeignKey(User,on_delete=models.CASCADE,null=True)

    updated_on = models.DateTimeField(auto_now=True)    
    created_on = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return self.acronym

examination_body/views.py
from django.shortcuts import render
from django.shortcuts import redirect
from django.utils.text import slugify
from django.core.exceptions import ObjectDoesNotExist

from user_management.models import User
from logs.models import ExaminationBodyLogs
from examination_body.models import ExaminationBody


# Create your views here.
def create(request):
    if request.method == "POST":
        user = request.user
        name = request.POST.get('name', '')
        acronym = request.POST.get('acronym', '')
        try:
            queryset = ExaminationBody.objects.create(
                name = name,
                acronym = acronym,
                slug = slugify(name),
                created_by = user
            )
            
            logs = ExaminationBodyLogs.objects.create(
                action = "Create",
                action_by = user,
                examination_body = queryset,
                values = f"Name - {name}, Acronym - {acronym}, Slug - {slugify(name)}"
            )
            return redirect("examination_body_app:view_all")
        except Exception as e:
            context = {"error": f"Error occured while saving examination body record --> {e}"}
            return render(request, 'examination_body/create.html', context)         
    else:
        context = {}
        return render(request, 'examination_body/create.html', context)

def view_all(request):
    try:
        record = ExaminationBody.objects.all().order_by('-created_on')
        context = {"record": record, "message": ""}
        return render(request, "examination_body/view_all.html", context)
    except ObjectDoesNotExist:
        context = {"error": "Examination bodies do not exist"}
        return render(request, "examination_body/view_all.html", context)

def update(request, pk):
    try:
        queryset = ExaminationBody.objects.get(pk=pk)
        context = {"queryset": queryset}
    except ObjectDoesNotExist as o:
        context = {"error": f"Examination Body record not found! --{o}"}
    except Exception as e:
        context = {"error": f"Error occured while trying to get Examination Body record! --> {e}"}
    return render(request, 'examination_body/update.html', context)

def update_post(request):
    try:                    
        if request.method == "POST":
            user = request.user
            pk = request.POST.get('pk', '')
            name = request.POST.get('name', '')
            acronym = request.POST.get('acronym', '')

            try:
                queryset = ExaminationBody.objects.get(pk=pk)
                queryset.name = name
                queryset.slug = slugify(name)
                queryset.acronym = acronym                
                queryset.save()

                logs = ExaminationBodyLogs.objects.create(
                    action = "Update",
                    action_by = user,
                    examination_body = queryset,
                    values = f"Name - {name}, Acronym - {acronym}, Slug - {slugify(name)}"
                )

                return redirect("examination_body_app:view_all")                
            except Exception as s:
                context = {"error": f"Error occured while trying to Update Examination Body record! --> {s}"}
    except ObjectDoesNotExist as o:
        context = {"error": f"Examination Body record not found! --{o}"}
    except Exception as e:
        context = {"error": f"Error occured while trying to get Examination Body record! --> {e}"}
    return render(request, 'examination_body/update.html', context)

examination_body/templates/examination_body/create.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
<div class="row">
    <div class="row">
        <div class="col-12"> 
            <div class="page-title-box">
                <div class="page-title-right">
                    <ol class="breadcrumb m-0">
                        <li class="breadcrumb-item"><a href="">Examination Body</a></li>                  
                        <li class="breadcrumb-item active">Create</li>
                    </ol>
                </div>
                <h4 class="page-title">Create Examination Body</h4>
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-body">
                <form method="POST" action="{% url 'examination_body_app:create_examination_body' %}">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="acronym" class="col-form-label">Acronym</label>
                        <input type="text" required class="form-control" id="acronym" name="acronym" placeholder="acronym" v-model="acronym">
                    </div>
                    <div class="form-group">
                        <label for="name" class="col-form-label">Name</label>
                        <input type="text" required class="form-control" id="name" name="name" placeholder="name" v-model="name">
                    </div>
                    <br>
                    <input type="submit" class="btn btn-primary" id="submit" name="submit" value="Save">
                </form>

            </div>
        </div>
    </div>
</div>
{% endblock %}

examination_body/templates/examination_body/update.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
<div class="row">
    <div class="row">
        <div class="col-12"> 
            <div class="page-title-box">
                <div class="page-title-right">
                    <ol class="breadcrumb m-0">
                        <li class="breadcrumb-item"><a href="">Examination Body</a></li>                  
                        <li class="breadcrumb-item active">Update</li>
                    </ol>
                </div>
                <h4 class="page-title">Update Examination Body</h4>
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-body">
                {% if error %}
                <div class="alert alert-danger alert-dismissible fade show" role="alert">
                    <strong>ERROR! </strong> {{error}}
                </div> 
                {% endif %}
                <form method="POST" action="{% url 'examination_body_app:update_post' %}">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="acronym" class="col-form-label">Acronym</label>
                        <input type="text" value="{{queryset.acronym}}" required class="form-control" id="acronym" name="acronym" placeholder="acronym" v-model="acronym">
                    </div>
                    <div class="form-group">
                        <label for="name" class="col-form-label">Name</label>
                        <input type="text" value="{{queryset.name}}" required class="form-control" id="name" name="name" placeholder="name" v-model="name">
                    </div>
                    <input hidden type="text" value="{{queryset.id}}" required class="form-control" id="pk" name="pk">
                    <br>
                    <input type="submit" class="btn btn-primary" id="submit" name="submit" value="Update">
                </form>

            </div>
        </div>
    </div>
</div>
{% endblock %}

examination_body/templates/examination_body/view_all.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
<div class="row">
    <div class="row">
        <div class="col-12"> 
            <div class="page-title-box">
                <div class="page-title-right">
                    <ol class="breadcrumb m-0">
                        <li class="breadcrumb-item"><a href="">Examination Body</a></li>                  
                        <li class="breadcrumb-item active">View All</li>
                    </ol>
                </div>
                <h4 class="page-title">Examination Bodies</h4>
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-body">
                
                <table class="table">
                    <thead class="thead-dark">
                        <tr>
                            <th> # </th>
                            <th> Acronym </th>
                            <th> Name </th>
                            <th> Slug </th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                    </tbody>
                        {% for data in record %}
                            <tr>
                                <td> {{forloop.counter}} </td>
                                <td> {{data.acronym}} </td>
                                <td> {{data.name}} </td>
                                <td> {{data.slug}} </td> 
                                <td> <a href="{% url 'examination_body_app:update' data.id %}"> <i class="fa fa-pencil" aria-hidden="true"></i> </a> </td>               
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>

            </div>
        </div>
    </div>
</div>
{% endblock %}