examination/urls.py
from django.urls import path

from examination import views

app_name = "examination_app"

urlpatterns = [
    path('create', views.create, name='create'),
    path('view/all', views.view_all, name='view_all'),
    path('update/<int:pk>', views.update, name='update'),
    path('update/post', views.update_post, name='update_post'),
]

muungano_online_exams/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('examination/', include('examination.urls')),
    path('examination/body/', include('examination_body.urls')),
    path('examination/paper/', include('examination_paper.urls')),
]

examination/models.py
from django.db import models

from examination_body.models import ExaminationBody

# Create your models here.
class Examination(models.Model):
    class Meta:
        db_table = "examination"
    slug = models.SlugField(max_length=255, null = True, blank = True)
    name = models.CharField(max_length=255, null = False, blank = False) # Kenya Certificate of Secondary Education
    acronym = models.CharField(max_length=255, null = False, blank = False) # KCSE
    
    examination_body = models.ForeignKey(ExaminationBody, on_delete=models.CASCADE) #KNEC

    updated_on = models.DateTimeField(auto_now=True)
    created_on = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.acronym

examination/views.py
from django.shortcuts import render
from django.shortcuts import redirect
from django.utils.text import slugify

from logs.models import ExaminationLogs
from examination.models import Examination
from examination_body.models import ExaminationBody
# Create your views here.

def create(request):
    if request.method == "POST":
        name = request.POST.get('name', '')
        acronym = request.POST.get('acronym', '')
        examination_body_id = request.POST.get('examination_body', '')   

        try:
            examination_body = ExaminationBody.objects.get(pk=examination_body_id)

            queryset = Examination.objects.create(
                name = name,
                acronym = acronym,
                slug = slugify(name),
                examination_body = examination_body
            )

            logs = ExaminationLogs.objects.create(
                action = "Create",
                action_by = user,
                examination = queryset,
                values = f"Name - {name}, Acronym - {acronym}, Slug - {slugify(name)}"
            )
            return redirect("examination_app:view_all")            
        except Exception as e:
            context = {"Error": "Error occured while saving examination record"}
            return render(request, 'examination/create.html', context)
    else:
        examination_body = ExaminationBody.objects.all().order_by('acronym')
        context = {"examination_body": examination_body}
        return render(request, 'examination/create.html', context)

def view_all(request):
    try:
        record = Examination.objects.all().order_by('-created_on')
        context = {"record": record, "message": ""}
        return render(request, "examination/view_all.html", context)
    except ObjectDoesNotExist:
        context = {"message": "Examinations do not exist"}
        return render(request, "examination/view_all.html", context)

def update(request, pk):
    try:
        queryset = Examination.objects.get(pk=pk)
        examination_body = ExaminationBody.objects.all().order_by('acronym')
        context = {"queryset": queryset, "examination_body": examination_body}
    except ObjectDoesNotExist as o:
        context = {"error": f"Examination record not found! --{o}"}
    except Exception as e:
        context = {"error": f"Error occured while trying to get Examination record! --> {e}"}
    return render(request, 'examination/update.html', context)

def update_post(request):
    try:                    
        if request.method == "POST":
            user = request.user
            pk = request.POST.get('pk', '')
            print(f"PK -- > {pk}")
            name = request.POST.get('name', '')
            print(f"Name -- > {name}")
            acronym = request.POST.get('acronym', '')
            print(f"Acronym -- > {acronym}")
            examination_body_id = request.POST.get('examination_body', '')
            print("Examination Body ID --> ", examination_body_id)
            
            try:
                examination_body = ExaminationBody.objects.get(pk=examination_body_id)
                queryset = Examination.objects.get(pk=pk)
                queryset.name = name                
                queryset.acronym = acronym
                queryset.slug = slugify(name)
                queryset.examination_body = examination_body   
                queryset.save()

                logs = ExaminationLogs.objects.create(
                    action = "Update",
                    action_by = user,
                    examination = queryset,
                    values = f"Name - {name}, Acronym - {acronym}, Slug - {slugify(name)}, Examination Body - {examination_body.acronym}"
                )

                return redirect("examination_app:view_all")                
            except Exception as s:
                context = {"error": f"Error occured while trying to Update Examination record! --> {s}"}
    except ObjectDoesNotExist as o:
        context = {"error": f"Examination Body record not found! --{o}"}
    except Exception as e:
        context = {"error": f"Error occured while trying to get Examination Body record! --> {e}"}
    return render(request, 'examination_body/update.html', context)

examination/templates/examination/create.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
<div class="row">
    <div class="row">
        <div class="col-12"> 
            <div class="page-title-box">
                <div class="page-title-right">
                    <ol class="breadcrumb m-0">
                        <li class="breadcrumb-item"><a href="">Examination</a></li>                  
                        <li class="breadcrumb-item active">Create</li>
                    </ol>
                </div>
                <h4 class="page-title">Create Examination</h4>
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-body">
                {% if error %}
                <div class="alert alert-danger alert-dismissible fade show" role="alert">
                    <strong>ERROR! </strong> {{error}}
                </div> 
                {% endif %}
                {% if success %}
                <div class="alert alert-success alert-dismissible fade show" role="alert">
                    <strong>Success! </strong> {{success}}
                </div> 
                {% endif %} 
                <form method="POST" action="{% url 'examination_app:create' %}">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="examination_body" class="col-form-label">Examination Body</label>
                        <select id="examination_body" name="examination_body" class="form-control ">
                            <option value="none" selected disabled hidden>
                                Examination Body
                            </option>
                            {% for val in examination_body %}    
                                <option value={{val.id}}>{{val}}</option>                                
                            {% endfor %}
                        </select>
                    </div>
                    <div class="form-group">
                        <label for="acronym" class="col-form-label">Acronym</label>
                        <input type="text" required class="form-control" id="acronym" name="acronym" placeholder="acronym" v-model="acronym">
                    </div>
                    <div class="form-group">
                        <label for="name" class="col-form-label">Name</label>
                        <input type="text" required class="form-control" id="name" name="name" placeholder="name" v-model="name">
                    </div>
                    <br>
                    <input type="submit" class="btn btn-primary" id="submit" name="submit" value="Save">
                </form>

            </div>
        </div>
    </div>
</div>
{% endblock %}













<h1> Create Examination </h1>
<form method="POST" action="{% url 'examination_app:create' %}">
    {% csrf_token %}
    <label for="examination_body" class="col-form-label">Examination Body</label>
    <select id="examination_body" name="examination_body">
        {% for data in examination_body %}
        <option value="data.id"> {{data.acronym}} </option>
        {% endfor %}
    </select>
    <br><br>

    <label for="acronym" class="col-form-label">Acronym</label>
    <input type="text" name="acronym", id="acronym" placeholder="Acronym">
    <br><br>

    <label for="name" class="col-form-label">Name</label>
    <input type="text" name="name", id="name" placeholder="Name">
    <br><br>

    <input type="submit" name="submit" value="Create">
</form>

examination/templates/examination/update.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
<div class="row">
    <div class="row">
        <div class="col-12"> 
            <div class="page-title-box">
                <div class="page-title-right">
                    <ol class="breadcrumb m-0">
                        <li class="breadcrumb-item"><a href="">Examination</a></li>                  
                        <li class="breadcrumb-item active">Update</li>
                    </ol>
                </div>
                <h4 class="page-title">Create Update</h4>
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-body">
                {% if error %}
                <div class="alert alert-danger alert-dismissible fade show" role="alert">
                    <strong>ERROR! </strong> {{error}}
                </div> 
                {% endif %}
                {% if success %}
                <div class="alert alert-success alert-dismissible fade show" role="alert">
                    <strong>Success! </strong> {{success}}
                </div> 
                {% endif %} 
                <form method="POST" action="{% url 'examination_app:update_post' %}">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="examination_body" class="col-form-label">Examination Body</label>
                        <select id="examination_body" name="examination_body" class="form-control ">
                            <option value="{{ queryset.examination_body }}" selected disabled hidden>
                                {{ queryset.examination_body }}
                            </option>
                            {% for val in examination_body %}    
                                <option value="{{val.id}}">{{val.acronym}}</option>                                
                            {% endfor %}
                        </select>
                    </div>
                    <div class="form-group">
                        <label for="acronym" class="col-form-label">Acronym</label>
                        <input type="text" value="{{ queryset.acronym }}" required class="form-control" id="acronym" name="acronym" placeholder="acronym" v-model="acronym">
                    </div>
                    <div class="form-group">
                        <label for="name" class="col-form-label">Name</label>
                        <input type="text" value="{{ queryset.name }}" required class="form-control" id="name" name="name" placeholder="name" v-model="name">
                    </div>
                    <input hidden type="text" value="{{queryset.id}}" required class="form-control" id="pk" name="pk">
                    <br>
                    <input type="submit" class="btn btn-primary" id="submit" name="submit" value="Update">
                </form>

            </div>
        </div>
    </div>
</div>
{% endblock %}













<h1> Create Examination </h1>
<form method="POST" action="{% url 'examination_app:create' %}">
    {% csrf_token %}
    <label for="examination_body" class="col-form-label">Examination Body</label>
    <select id="examination_body" name="examination_body">
        {% for data in examination_body %}
        <option value="data.id"> {{data.acronym}} </option>
        {% endfor %}
    </select>
    <br><br>

    <label for="acronym" class="col-form-label">Acronym</label>
    <input type="text" name="acronym", id="acronym" placeholder="Acronym">
    <br><br>

    <label for="name" class="col-form-label">Name</label>
    <input type="text" name="name", id="name" placeholder="Name">
    <br><br>

    <input type="submit" name="submit" value="Create">
</form>

examination/templates/examination/view_all.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
<div class="row">
    <div class="row">
        <div class="col-12"> 
            <div class="page-title-box">
                <div class="page-title-right">
                    <ol class="breadcrumb m-0">
                        <li class="breadcrumb-item"><a href="">Examination</a></li>                  
                        <li class="breadcrumb-item active">View All</li>
                    </ol>
                </div>
                <h4 class="page-title">Examination</h4>
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-body">
                
                <table class="table">
                    <thead class="thead-dark">
                        <tr>
                            <th> # </th>
                            <th> Acronym </th>
                            <th> Name </th>
                            <th> Exam Body </th>
                            <th> Slug </th>                            
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                    </tbody>
                        {% for data in record %}
                            <tr>
                                <td> {{forloop.counter}} </td>
                                <td> {{data.acronym}} </td>
                                <td> {{data.name}} </td>
                                <td> {{data.examination_body.acronym}} </td>
                                <td> {{data.slug}} </td>
                                <td> <a href="{% url 'examination_app:update' data.id %}"> <i class="fa fa-pencil" aria-hidden="true"></i> </a> </td>               
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>

            </div>
        </div>
    </div>
</div>
{% endblock %}