examination/urls.py
from django.urls import path

from examination import views

app_name = "examination_app"

urlpatterns = [
    path('create', views.create, name='create'),
    path('view/all', views.view_all, name='view_all'),
    path('update/<int:pk>', views.update, name='update'),
    path('update/post', views.update_post, name='update_post'),
]

examination_paper/urls.py
from django.urls import path

from examination_paper import views

app_name = "examination_paper_app"

urlpatterns = [
    path('create', views.create, name='create'),
    path('view/all', views.view_all, name='view_all'),
    path('view/<int:pk>', views.view_single, name='view_single'),
    path('create/insturctions/<int:pk>', views.create_instructions, name='create_instructions'),
    path('create/insturctions/post', views.create_instructions_post, name='create_instructions_post'),
]

muungano_online_exams/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('examination/', include('examination.urls')),
    path('examination/body/', include('examination_body.urls')),
    path('examination/paper/', include('examination_paper.urls')),
]

examination_paper/models.py
from django.db import models

from examination.models import Examination

# Create your models here.
class ExaminationPaper(models.Model):
    class Meta:
        db_table = "examination_paper"
    year = models.IntegerField()    
    slug = models.SlugField(max_length=255, null = True, blank = True)
    name = models.CharField(max_length=255, null = False, blank = False) # Paper 1
    # section = models.SlugField(max_length=255, null = True, blank = True)
    subject = models.SlugField(max_length=255, null = True, blank = True)
    exam_duration  = models.CharField(max_length=255, null = True, blank = True)
    
    examination = models.ForeignKey(Examination, on_delete=models.CASCADE, null=False)    
    
    updated_on = models.DateTimeField(auto_now=True)
    created_on = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

examination_paper/views.py
from django.shortcuts import render
from django.shortcuts import redirect
from django.utils.text import slugify
from django.core.exceptions import ObjectDoesNotExist

from examination.models import Examination
from instructions.models import Instruction
from examination_paper.models import ExaminationPaper
# Create your views here.

def create(request):
    if request.method == "POST":
        name = request.POST.get('name', '')
        year = request.POST.get('year', '')        
        subject = request.POST.get('subject', '')
        examination = request.POST.get('examination', '')
        exam_duration = request.POST.get('exam_duration', '')

        print(f"Name --> {name}")
        print(f"Year --> {year}")
        print(f"Subject --> {subject}")
        print(f"Examination --> {examination}")
        print(f"Exam Duration --> {exam_duration}")
        
        try:
            examination_queryset = Examination.objects.get(pk=examination)
            slug_field = f"{examination_queryset.acronym} {year} {subject} {name}"
            queryset = ExaminationPaper.objects.create(
                name = name,
                year = year,                
                subject = subject,
                slug = slugify(slug_field),
                exam_duration = exam_duration,
                examination = examination_queryset,
            )
            return redirect("examination_paper_app:create_instructions", pk=queryset.pk)
        except Exception as e:
            examination = Examination.objects.all()
            message = f"Error Saving Examination Paper record --> {str(e)}"
            print(f"{message}")
            context = {
                "error": message,
                "examination": examination,
            }
            return render(request, 'examination_paper/create.html', context)
    else:
        examination = Examination.objects.all()
        context = {
            "examination": examination,
        }
        return render(request, 'examination_paper/create.html', context)

def create_instructions(request, pk):
    if request.method == "GET":
        exam_paper = ExaminationPaper.objects.get(pk=pk)
        context = {
            "exam_paper": exam_paper,
        }
        return render(request, 'examination_paper/create_instructions.html', context)

def create_instructions_post(request):
    if request.method == "POST":
        exam_paper = request.POST.get('exam_paper', '')
        instructions = request.POST.get('instructions', '')  

        try:
            exam_paper_queryset = ExaminationPaper.objects.get(pk=exam_paper)
            queryset = Instruction.objects.create(instructions = instructions, examination_paper = exam_paper_queryset)
            # proceed to add Questions
        except Exception as e:
            message = f"Error occured while saving Instructions --> {str(e)}"
            exam_paper = ExaminationPaper.objects.get(pk=pk)
            context = {
                "error": message,
                "exam_paper": exam_paper,
            }
            return render(request, 'examination_paper/create_instructions.html', context)

def view_all(request):
    try:
        record = ExaminationPaper.objects.all().order_by('-created_on')
        context = {"record": record, "message": ""}
        return render(request, "examination_paper/view_all.html", context)
    except ObjectDoesNotExist:
        context = {"error": "Examination Papers do not exist"}
        return render(request, "examination_paper/view_all.html", context)

def view_single(request, pk):
    try:
        record = ExaminationPaper.objects.get(pk=pk)
        context = {
            "message": "",
            "record": record
        }
        return render(request, "examination_paper/view_single.html", context)
    except ObjectDoesNotExist:
        context = {"error": "Examination Paper do not exist"}
        return render(request, "examination_paper/view_all.html", context)

examination_paper/templates/examination_paper/create.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
<div class="row">
    <div class="row">
        <div class="col-12"> 
            <div class="page-title-box">
                <div class="page-title-right">
                    <ol class="breadcrumb m-0">
                        <li class="breadcrumb-item"><a href="">Examination</a></li>                        
                        <li class="breadcrumb-item"><a href="">Exam Paper</a></li>                    
                        <li class="breadcrumb-item active">Create</li>
                    </ol>
                </div>
                <h4 class="page-title">Create Examination Paper</h4>
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-body">
                {% if error %}
                <div class="alert alert-danger alert-dismissible fade show" role="alert">
                    <strong>ERROR! </strong> {{error}}
                </div> 
                {% endif %}
                <form method="POST" action="{% url 'examination_paper_app:create' %}">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="examination" class="col-form-label">Examination</label>
                        <select id="examination" name="examination" class="form-control ">
                            <option value="none" selected disabled hidden>
                                Examination
                            </option>
                            {% for val in examination %}    
                                <option value={{val.id}}>{{val}}</option>                                
                            {% endfor %} 
                        </select>
                    </div>

                    <div class="form-row">
                        <div class="form-group">
                            <label for="year" class="col-form-label">Year</label>
                            <input type="text" required class="form-control" id="year" name="year"
                                placeholder="Examination Year" v-model="year">
                                <p id="error-message"></p>
                        </div>
                    </div>

                    <div class="form-row">
                        <div class="form-group">
                            <label for="subject" class="col-form-label">Subject</label>
                            <input type="text" required class="form-control" id="subject" name="subject"
                                placeholder="Subject" v-model="subject">
                                <p id="error-message"></p>
                        </div>
                    </div>

                    <div class="form-row">
                        <div class="form-group">
                            <label for="name" class="col-form-label">Examination Name</label>
                            <input type="text" required class="form-control" id="name" name="name"
                                placeholder="Examination Name" v-model="name">
                                <p id="error-message"></p>
                        </div>
                    </div>

                    <div class="form-row">
                        <div class="form-group">
                            <label for="exam_duration" class="col-form-label">Examination Duration (In Minutes)</label>
                            <input type="text" required class="form-control" id="exam_duration" name="exam_duration"
                                placeholder="Examination Duration" v-model="exam_duration">
                                <p id="error-message"></p>
                        </div>
                    </div>

                    <br>
                    <input type="submit" class="btn btn-primary" id="submit" name="submit" value="Next">
                    
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

examination_paper/templates/examination_paper/create_instructions.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
<div class="row">
    <div class="row">
        <div class="col-12"> 
            <div class="page-title-box">
                <div class="page-title-right">
                    <ol class="breadcrumb m-0">
                        <li class="breadcrumb-item"><a href="">Examination</a></li>                        
                        <li class="breadcrumb-item"><a href="">Exam Paper</a></li>
                        <li class="breadcrumb-item"><a href="">Instructions</a></li>                    
                        <li class="breadcrumb-item active">Create</li>
                    </ol>
                </div>
                
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-body">
                {% if error %}
                <div class="alert alert-danger alert-dismissible fade show" role="alert">
                    <strong>ERROR! </strong> {{error}}
                </div> 
                {% endif %}
                <div class="row" style="text-align: center;">
                    <div class="col-12" ><h1>{{exam_paper.examination.examination_body.name}}</h1></div>
                    <div class="col-12" ><h1>{{exam_paper.examination.name}}</h1></div>
                    <div class="col-12" ><h1>{{exam_paper.subject}}</h1></div>
                    <div class="col-12" ><h1>{{exam_paper.name}} {{exam_paper.year}}</h1></div>
                    <div class="col-12" ><h3>{{exam_paper.exam_duration}} Minutes</h3></div>
                </div>

                <div class="row"> <div class="col-12" ><h4 class="page-title">Create Instructions</h4></div> </div>
                <form method="POST" action="{% url 'examination_paper_app:create_instructions_post' %}">
                    {% csrf_token %}
                    <textarea id="instructions" name="instructions"></textarea>
                    <input type="text" value="{{exam_paper.pk}}" required class="form-control" id="exam_paper" name="exam_paper">
                    <br>
                    <input type="submit" class="btn btn-primary" id="submit" name="submit" value="Next">
                    
                </form>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript" src="{% static 'ckeditor/ckeditor-init.js' %}"></script>
<script type="text/javascript" src="{% static 'ckeditor/ckeditor/ckeditor.js' %}"></script>
<script>
    // Replace the <textarea id="editor1"> with a CKEditor 4
    // instance, using default configuration.
    CKEDITOR.replace( 'instructions' );
</script>
{% endblock %}

examination_paper/templates/examination_paper/view_all.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
<div class="row">
    <div class="row">
        <div class="col-12"> 
            <div class="page-title-box">
                <div class="page-title-right">
                    <ol class="breadcrumb m-0">
                        <li class="breadcrumb-item"><a href="">Examination Paper</a></li>                  
                        <li class="breadcrumb-item active">View All</li>
                    </ol>
                </div>
                <h4 class="page-title">Examination Paper</h4>
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-body">
                
                <table class="table">
                    <thead class="thead-dark">
                        <tr>
                            <th> # </th>
                            <th> Examination </th>
                            <th> Subject </th>
                            <th> Paper </th>
                            <th> Year </th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                    </tbody>
                        {% for data in record %}
                            <tr>
                                <td> {{forloop.counter}} </td>
                                <td> {{data.examination}} </td>
                                <td> {{data.subject}} </td>
                                <td> {{data.name}} </td>
                                <td> {{data.year}} </td> 
                                <td> <a href="{% url 'examination_paper_app:view_single' data.id %}"> <i class="fa fa-folder-open-o" aria-hidden="true"></i> </a> </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>

            </div>
        </div>
    </div>
</div>
{% endblock %}

examination_paper/templates/examination_paper/view_single.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
<div class="row">
    <div class="row">
        <div class="col-12"> 
            <div class="page-title-box">
                <div class="page-title-right">
                    <ol class="breadcrumb m-0">
                        <li class="breadcrumb-item"><a href="">Examination Paper</a></li>                  
                        <li class="breadcrumb-item active">View</li>
                    </ol>
                </div>
                <h4 class="page-title">Examination paper</h4>
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-body">
                                

            </div>
        </div>
    </div>
</div>
{% endblock %}