examination/urls.py
from django.urls import path

from examination import views

app_name = "examination_app"

urlpatterns = [
    path('create', views.create, name='create'),
    path('view/all', views.view_all, name='view_all'),
    path('update/<int:pk>', views.update, name='update'),
    path('update/post', views.update_post, name='update_post'),
]

examination_body/urls.py
from django.urls import path

from examination_body import views

app_name = "examination_body_app"

urlpatterns = [
    path('create', views.create, name='create'),
    path('view/all', views.view_all, name='view_all'),
    path('update/<int:pk>', views.update, name='update'),
    path('update/post', views.update_post, name='update_post'),
]

examination_paper/urls.py
from django.urls import path

from examination_paper import views

app_name = "examination_paper_app"

urlpatterns = [
    path('create', views.create, name='create'),
    path('view/all', views.view_all, name='view_all'),
    path('view/<int:pk>', views.view_single, name='view_single'),
    path('create/insturctions/<int:pk>', views.create_instructions, name='create_instructions'),
    path('create/insturctions/post', views.create_instructions_post, name='create_instructions_post'),
]

muungano_online_exams/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('examination/', include('examination.urls')),
    path('examination/body/', include('examination_body.urls')),
    path('examination/paper/', include('examination_paper.urls')),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" type="text/css" />
    <link href="{% static 'css/menu-styles.css' %}" rel="stylesheet" type="text/css" />
    <link href="{% static 'font-awesome/css/font-awesome.css' %}" rel="stylesheet" type="text/css" />
    
    <!-- <script type="text/javascript" src="{% static 'js/ckeditor/ckeditor.js' %}"></script> -->
    <!-- Include CSS Files -->
</head>
<body>
    <div class="container-fluid">
        <nav class="navbar navbar-light bg-light" >
            Navigation
        </nav>

        <div class="row">
            <div class="col-2 menu">
                <ul>
                    <li> 
                        <a href="">Examination Body</a> 
                        <ul>
                            <li> <a href="{% url 'examination_body_app:create' %}">Create</a> </li>
                            <li> <a href="{% url 'examination_body_app:view_all' %}">View All</a> </li>
                        </ul>
                    </li>

                    <li> 
                        <a href="">Examination</a> 
                        <ul>
                            <li> <a href="{% url 'examination_app:create' %}">Create</a> </li>
                            <li> <a href="{% url 'examination_app:view_all' %}">View All</a> </li>
                        </ul>
                    </li>

                    <li> 
                        <a href="">Examination Paper</a> 
                        <ul>
                            <li> <a href="{% url 'examination_paper_app:create' %}">Create</a> </li>
                            <li> <a href="{% url 'examination_paper_app:view_all' %}">View All</a> </li>
                        </ul>
                    </li>
                </ul>
            </div>
            <div class="col-10">{% block content%} {% endblock%}</div>
        </div>
        
    </div>    
    <script src="{% static 'js/jquery.min.js' %}" type="text/javascript"></script>    
</body>
</html>